#:schema node_modules/wrangler/config-schema.json
name = "freecaraxes"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "www.freecaraxes.org", custom_domain = true },
  { pattern = "freecaraxes.org", custom_domain = true }
]


[durable_objects]
bindings = [
  { name = "DONATIONS", class_name = "DurableDonation" }
]

  [[migrations]]
  tag = "v1" # Should be unique for each entry
  new_classes = ["DurableDonation"]
